apiVersion: v1
kind: Config
clusters:
- cluster:
    server: http://localhost:8080
  name: dummy-cluster
contexts:
- context:
    cluster: dummy-cluster
    user: dummy-user
  name: dummy-context
current-context: dummy-context
users:
- name: dummy-user
