//  Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
// 
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
// 
//      http://www.apache.org/licenses/LICENSE-2.0
// 
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

// Code generated by client-gen and gRPC overlay. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/nvidia/nvsentinel/client-go/client/versioned/typed/device/v1alpha1"
	"google.golang.org/grpc"
	testing "k8s.io/client-go/testing"
)

type FakeDeviceV1alpha1 struct {
	*testing.Fake
}

func (c *FakeDeviceV1alpha1) GPUs() v1alpha1.GPUInterface {
	return newFakeGPUs(c)
}

// ClientConn returns a ClientConn that is used to communicate
// with gRPC server by this client implementation.
//
// Note: the Fake implementation uses the ObjectTracker memory store, not an actual gRPC connection.
func (c *FakeDeviceV1alpha1) ClientConn() grpc.ClientConnInterface {
	var ret *grpc.ClientConn
	return ret
}
