//  Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/nvidia/nvsentinel/api/device/v1alpha1"
	devicev1alpha1 "github.com/nvidia/nvsentinel/client-go/client/versioned/typed/device/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeGPUs implements GPUInterface
type fakeGPUs struct {
	*gentype.FakeClientWithList[*v1alpha1.GPU, *v1alpha1.GPUList]
	Fake *FakeDeviceV1alpha1
}

func newFakeGPUs(fake *FakeDeviceV1alpha1) devicev1alpha1.GPUInterface {
	return &fakeGPUs{
		gentype.NewFakeClientWithList[*v1alpha1.GPU, *v1alpha1.GPUList](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("gpus"),
			v1alpha1.SchemeGroupVersion.WithKind("GPU"),
			func() *v1alpha1.GPU { return &v1alpha1.GPU{} },
			func() *v1alpha1.GPUList { return &v1alpha1.GPUList{} },
			func(dst, src *v1alpha1.GPUList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.GPUList) []*v1alpha1.GPU { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.GPUList, items []*v1alpha1.GPU) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
