#!/bin/bash

# Applies custom gRPC overlays to the code generated by client-gen.

set -euo pipefail

OVERLAY_ROOT="hack/overlays"
BOILERPLATE="hack/boilerplate_overlay.go.txt"

echo "Applying overlays from ${OVERLAY_ROOT}..."

if [[ ! -f "${BOILERPLATE}" ]]; then
    echo "Error: Boilerplate file '${BOILERPLATE}' not found."
    exit 1
fi

if [[ ! -f "go.mod" ]]; then
    echo "Error: This script must be run from the repository root."
    exit 1
fi

find "${OVERLAY_ROOT}" -type f -name "*.go" | while read -r src; do
  # Strip the 'hack/overlays/' prefix to get the target path
  # e.g. hack/overlays/client/versioned/clientset.go -> client/versioned/clientset.go
  dest="${src#"${OVERLAY_ROOT}"/}"
  mkdir -p "$(dirname "${dest}")"
  cat "${BOILERPLATE}" "${src}" > "${dest}"
  echo "${src} -> ${dest}"
done
