device-apiserver:
  image:
    tag: latest

#  securityContext:
#    runAsUser: 0
#    runAsNonRoot: false

#  pprof:
#    enabled: true

  serviceMonitor:
    enabled: false

#  resources:
#    requests:
#      cpu: 500m 
#      memory: 256Mi
#    limits:
#      cpu: "1"
#      memory: 512Mi
#
#  env:
#    - name: GOMAXPROCS
#      value: "2"
#    - name: GOMEMLIMIT
#      value: "400MiB"

  nodeSelector:
    kubernetes.io/hostname: device-api-control-plane

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: Exists

#  extraArgs:
#    - -v=2
#    - --etcd-compaction-batch-size=100
#    - --database-connection-max-lifetime=2m
#    - --grpc-max-connection-idle=10m
#    - --etcd-compaction-interval=1m
#    - --storage-backend=etcd3
#    - --database-path=sqlite:///var/lib/nvidia-device-api/state.db?_busy_timeout=5000&_cache_size=-16000&_foreign_keys=ON&_journal_mode=WAL&_locking_mode=NORMAL&_mmap_size=33554432&_page_size=4096&_synchronous=NORMAL&_temp_store=MEMORY&_txlock=immediate
#    - --database-max-open-connections=2
#    - --database-max-idle-connections=2
#    - --grpc-max-streams-per-connection=100
#    - --grpc-write-buffer-size=262144
#    - --grpc-read-buffer-size=262144
#    - --grpc-max-recv-msg-size=4194304
#    - --grpc-max-send-msg-size=4194304
#    - --grpc-initial-window-size=4194304
#    - --grpc-initial-connection-window-size=4194304


nvml-provider:
  image:
    tag: latest

  serviceMonitor:
    enabled: false

  nodeSelector:
    kubernetes.io/hostname: device-api-control-plane

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: Exists
