// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package v1alpha1

import (
	v1alpha1 "github.com/nvidia/nvsentinel/internal/generated/proto/device/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
)

type ConverterImpl struct{}

func (c *ConverterImpl) FromProtobuf(source *v1alpha1.Gpu) GPU {
	var v1alpha1GPU GPU
	if source != nil {
		v1alpha1GPU.TypeMeta = FromProtobufTypeMeta(source)
		v1alpha1GPU.ObjectMeta = c.FromProtobufObjectMeta((*source).Metadata)
		v1alpha1GPU.Spec = c.FromProtobufSpec((*source).Spec)
		v1alpha1GPU.Status = c.FromProtobufStatus((*source).Status)
	}
	return v1alpha1GPU
}
func (c *ConverterImpl) FromProtobufCondition(source *v1alpha1.Condition) v1.Condition {
	var v1Condition v1.Condition
	if source != nil {
		v1Condition.Type = (*source).Type
		v1Condition.Status = v1.ConditionStatus((*source).Status)
		v1Condition.LastTransitionTime = FromProtobufTimestamp((*source).LastTransitionTime)
		v1Condition.Reason = (*source).Reason
		v1Condition.Message = (*source).Message
	}
	return v1Condition
}
func (c *ConverterImpl) FromProtobufList(source *v1alpha1.GpuList) *GPUList {
	var pV1alpha1GPUList *GPUList
	if source != nil {
		var v1alpha1GPUList GPUList
		v1alpha1GPUList.TypeMeta = FromProtobufListTypeMeta(source)
		v1alpha1GPUList.ListMeta = c.FromProtobufListMeta((*source).Metadata)
		if (*source).Items != nil {
			v1alpha1GPUList.Items = make([]GPU, len((*source).Items))
			for i := 0; i < len((*source).Items); i++ {
				v1alpha1GPUList.Items[i] = c.FromProtobuf((*source).Items[i])
			}
		}
		pV1alpha1GPUList = &v1alpha1GPUList
	}
	return pV1alpha1GPUList
}
func (c *ConverterImpl) FromProtobufListMeta(source *v1alpha1.ListMeta) v1.ListMeta {
	var v1ListMeta v1.ListMeta
	if source != nil {
		v1ListMeta.ResourceVersion = (*source).ResourceVersion
	}
	return v1ListMeta
}
func (c *ConverterImpl) FromProtobufObjectMeta(source *v1alpha1.ObjectMeta) v1.ObjectMeta {
	var v1ObjectMeta v1.ObjectMeta
	if source != nil {
		v1ObjectMeta.Name = (*source).Name
		v1ObjectMeta.Namespace = (*source).Namespace
		v1ObjectMeta.UID = types.UID((*source).Uid)
		v1ObjectMeta.ResourceVersion = (*source).ResourceVersion
		v1ObjectMeta.Generation = (*source).Generation
		v1ObjectMeta.CreationTimestamp = FromProtobufTimestamp((*source).CreationTimestamp)
	}
	return v1ObjectMeta
}
func (c *ConverterImpl) FromProtobufSpec(source *v1alpha1.GpuSpec) GPUSpec {
	var v1alpha1GPUSpec GPUSpec
	if source != nil {
		v1alpha1GPUSpec.UUID = (*source).Uuid
	}
	return v1alpha1GPUSpec
}
func (c *ConverterImpl) FromProtobufStatus(source *v1alpha1.GpuStatus) GPUStatus {
	var v1alpha1GPUStatus GPUStatus
	if source != nil {
		if (*source).Conditions != nil {
			v1alpha1GPUStatus.Conditions = make([]v1.Condition, len((*source).Conditions))
			for i := 0; i < len((*source).Conditions); i++ {
				v1alpha1GPUStatus.Conditions[i] = c.FromProtobufCondition((*source).Conditions[i])
			}
		}
		if (*source).RecommendedAction != nil {
			v1alpha1GPUStatus.RecommendedAction = *(*source).RecommendedAction
		}
	}
	return v1alpha1GPUStatus
}
func (c *ConverterImpl) ToProtobuf(source GPU) *v1alpha1.Gpu {
	var v1alpha1Gpu v1alpha1.Gpu
	v1alpha1Gpu.Metadata = c.ToProtobufObjectMeta(source.ObjectMeta)
	v1alpha1Gpu.Spec = c.ToProtobufSpec(source.Spec)
	v1alpha1Gpu.Status = c.ToProtobufStatus(source.Status)
	return &v1alpha1Gpu
}
func (c *ConverterImpl) ToProtobufCondition(source v1.Condition) *v1alpha1.Condition {
	var v1alpha1Condition v1alpha1.Condition
	v1alpha1Condition.Type = source.Type
	v1alpha1Condition.Status = string(source.Status)
	pInt64 := source.ObservedGeneration
	v1alpha1Condition.ObservedGeneration = &pInt64
	v1alpha1Condition.LastTransitionTime = ToProtobufTimestamp(source.LastTransitionTime)
	v1alpha1Condition.Reason = source.Reason
	v1alpha1Condition.Message = source.Message
	return &v1alpha1Condition
}
func (c *ConverterImpl) ToProtobufDeleteOptions(source v1.DeleteOptions) *v1alpha1.DeleteOptions {
	var v1alpha1DeleteOptions v1alpha1.DeleteOptions
	v1alpha1DeleteOptions.Preconditions = c.ToProtobufPreconditions(source.Preconditions)
	return &v1alpha1DeleteOptions
}
func (c *ConverterImpl) ToProtobufGetOptions(source v1.GetOptions) *v1alpha1.GetOptions {
	var v1alpha1GetOptions v1alpha1.GetOptions
	pString := source.ResourceVersion
	v1alpha1GetOptions.ResourceVersion = &pString
	return &v1alpha1GetOptions
}
func (c *ConverterImpl) ToProtobufList(source *GPUList) *v1alpha1.GpuList {
	var pV1alpha1GpuList *v1alpha1.GpuList
	if source != nil {
		var v1alpha1GpuList v1alpha1.GpuList
		v1alpha1GpuList.Metadata = c.ToProtobufListMeta((*source).ListMeta)
		if (*source).Items != nil {
			v1alpha1GpuList.Items = make([]*v1alpha1.Gpu, len((*source).Items))
			for i := 0; i < len((*source).Items); i++ {
				v1alpha1GpuList.Items[i] = c.ToProtobuf((*source).Items[i])
			}
		}
		pV1alpha1GpuList = &v1alpha1GpuList
	}
	return pV1alpha1GpuList
}
func (c *ConverterImpl) ToProtobufListMeta(source v1.ListMeta) *v1alpha1.ListMeta {
	var v1alpha1ListMeta v1alpha1.ListMeta
	v1alpha1ListMeta.ResourceVersion = source.ResourceVersion
	return &v1alpha1ListMeta
}
func (c *ConverterImpl) ToProtobufListOptions(source v1.ListOptions) *v1alpha1.ListOptions {
	var v1alpha1ListOptions v1alpha1.ListOptions
	pString := source.ResourceVersion
	v1alpha1ListOptions.ResourceVersion = &pString
	pString2 := c.v1ResourceVersionMatchToString(source.ResourceVersionMatch)
	v1alpha1ListOptions.ResourceVersionMatch = &pString2
	if source.TimeoutSeconds != nil {
		xint64 := *source.TimeoutSeconds
		v1alpha1ListOptions.TimeoutSeconds = &xint64
	}
	return &v1alpha1ListOptions
}
func (c *ConverterImpl) ToProtobufObjectMeta(source v1.ObjectMeta) *v1alpha1.ObjectMeta {
	var v1alpha1ObjectMeta v1alpha1.ObjectMeta
	v1alpha1ObjectMeta.Name = source.Name
	v1alpha1ObjectMeta.ResourceVersion = source.ResourceVersion
	v1alpha1ObjectMeta.Namespace = source.Namespace
	v1alpha1ObjectMeta.Uid = string(source.UID)
	v1alpha1ObjectMeta.Generation = source.Generation
	v1alpha1ObjectMeta.CreationTimestamp = ToProtobufTimestamp(source.CreationTimestamp)
	return &v1alpha1ObjectMeta
}
func (c *ConverterImpl) ToProtobufPatchOptions(source v1.PatchOptions) *v1alpha1.PatchOptions {
	var v1alpha1PatchOptions v1alpha1.PatchOptions
	_ = source
	return &v1alpha1PatchOptions
}
func (c *ConverterImpl) ToProtobufPreconditions(source *v1.Preconditions) *v1alpha1.Preconditions {
	var pV1alpha1Preconditions *v1alpha1.Preconditions
	if source != nil {
		var v1alpha1Preconditions v1alpha1.Preconditions
		if (*source).UID != nil {
			xstring := string(*(*source).UID)
			v1alpha1Preconditions.Uid = &xstring
		}
		if (*source).ResourceVersion != nil {
			xstring2 := *(*source).ResourceVersion
			v1alpha1Preconditions.ResourceVersion = &xstring2
		}
		pV1alpha1Preconditions = &v1alpha1Preconditions
	}
	return pV1alpha1Preconditions
}
func (c *ConverterImpl) ToProtobufSpec(source GPUSpec) *v1alpha1.GpuSpec {
	var v1alpha1GpuSpec v1alpha1.GpuSpec
	v1alpha1GpuSpec.Uuid = source.UUID
	return &v1alpha1GpuSpec
}
func (c *ConverterImpl) ToProtobufStatus(source GPUStatus) *v1alpha1.GpuStatus {
	var v1alpha1GpuStatus v1alpha1.GpuStatus
	if source.Conditions != nil {
		v1alpha1GpuStatus.Conditions = make([]*v1alpha1.Condition, len(source.Conditions))
		for i := 0; i < len(source.Conditions); i++ {
			v1alpha1GpuStatus.Conditions[i] = c.ToProtobufCondition(source.Conditions[i])
		}
	}
	pString := source.RecommendedAction
	v1alpha1GpuStatus.RecommendedAction = &pString
	return &v1alpha1GpuStatus
}
func (c *ConverterImpl) ToProtobufUpdateOptions(source v1.UpdateOptions) *v1alpha1.UpdateOptions {
	var v1alpha1UpdateOptions v1alpha1.UpdateOptions
	_ = source
	return &v1alpha1UpdateOptions
}
func (c *ConverterImpl) v1ResourceVersionMatchToString(source v1.ResourceVersionMatch) string {
	return string(source)
}
