//  Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

// Code generated by service-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"fmt"
	"path"
	"reflect"
	"time"

	devicev1alpha1 "github.com/nvidia/nvsentinel/api/device/v1alpha1"
	errors "github.com/nvidia/nvsentinel/pkg/grpc/errors"
	pb "github.com/nvidia/nvsentinel/internal/generated/device/v1alpha1"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/emptypb"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/uuid"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/apiserver/pkg/storage"
	"k8s.io/apiserver/pkg/storage/storagebackend/factory"
	"k8s.io/klog/v2"
)

type gpuService struct {
	pb.UnimplementedGpuServiceServer
	storage  storage.Interface
	destroyFunc factory.DestroyFunc
}

func NewGPUService(storage storage.Interface, destroyFunc factory.DestroyFunc) *gpuService {
	return &gpuService{
		storage:  storage,
		destroyFunc: destroyFunc,
	}
}

func (s *gpuService) Name() string {
	return pb.GpuService_ServiceDesc.ServiceName
}

func (s *gpuService) IsReady() bool {
	if s.storage == nil {
		return false
	}
	return s.storage.ReadinessCheck() == nil
}

func (s *gpuService) Cleanup() {
	if s.destroyFunc != nil {
		klog.V(2).InfoS("Shutting down storage backend", "service", s.Name())
		s.destroyFunc()
	}
}

func (s *gpuService) storageKey(ns string, name string) string {
	base := path.Join("/", devicev1alpha1.SchemeGroupVersion.Group, "gpus")

	if ns == "" && name != "" {
		ns = "default"
	}

	// Pattern: /device.nvidia.com/gpus/<namespace>/<name>
	return path.Join(base, ns, name)
}

func (s *gpuService) GetGpu(ctx context.Context, req *pb.GetGpuRequest) (*pb.GetGpuResponse, error) {
	logger := klog.FromContext(ctx)

	if req.GetName() == "" {
		return nil, status.Error(codes.InvalidArgument, "name is required")
	}

	name := req.GetName()
	ns := req.GetNamespace()
	reqRV := ""
	if req.GetOpts() != nil {
		reqRV = req.GetOpts().GetResourceVersion()
	}

	key := s.storageKey(ns, name)
	opts := storage.GetOptions{
		ResourceVersion: reqRV,
	}

	gpu := &devicev1alpha1.GPU{}
	if err := s.storage.Get(ctx, key, opts, gpu); err != nil {
		return nil, errors.NewGRPCError(err, "gpus", name)
	}

	logger.V(4).Info("Retrieved GPU", "name", name, "namespace", ns)

	return &pb.GetGpuResponse{
		Gpu: devicev1alpha1.ToProto(gpu),
	}, nil
}

func (s *gpuService) ListGpus(ctx context.Context, req *pb.ListGpusRequest) (*pb.ListGpusResponse, error) {
	logger := klog.FromContext(ctx)

	ns := req.GetNamespace()
	reqRV := ""
	if req.GetOpts() != nil {
		reqRV = req.GetOpts().GetResourceVersion()
	}
	reqRVM := ""
	if req.GetOpts() != nil {
		reqRVM = req.GetOpts().GetResourceVersionMatch()
	}

	key := s.storageKey(ns, "")
	opts := storage.ListOptions{
		ResourceVersion: reqRV,
		ResourceVersionMatch: metav1.ResourceVersionMatch(reqRVM),
		Recursive:       true,
		Predicate:       storage.Everything, // TODO: selection predicate
	}

	var gpus devicev1alpha1.GPUList
	if err := s.storage.GetList(ctx, key, opts, &gpus); err != nil {
		if storage.IsNotFound(err) {
			currRV, _ := s.storage.GetCurrentResourceVersion(ctx)
			return &pb.ListGpusResponse{
				GpuList: &pb.GpuList{
					Metadata: &pb.ListMeta{
						ResourceVersion: fmt.Sprintf("%d", currRV),
					},
					Items: []*pb.Gpu{},
				},
			}, nil
		}
		return nil, errors.NewGRPCError(err, "gpus", "")
	}

	logger.V(4).Info("Listed GPUs",
		"namespace", ns,
		"count", len(gpus.Items),
		"resourceVersion", gpus.GetListMeta().GetResourceVersion(),
	)

	return &pb.ListGpusResponse{
		GpuList: devicev1alpha1.ToProtoList(&gpus),
	}, nil
}

func (s *gpuService) WatchGpus(req *pb.WatchGpusRequest, stream pb.GpuService_WatchGpusServer) error {
	ctx := stream.Context()
	logger := klog.FromContext(ctx)

	ns := req.GetNamespace()
	reqRV := ""
	var timeoutSeconds *int64
	if req.GetOpts() != nil {
		reqRV = req.GetOpts().GetResourceVersion()
		timeoutSeconds = req.GetOpts().TimeoutSeconds
	}

	if timeoutSeconds != nil && *timeoutSeconds > 0 {
		timeout := time.Duration(*timeoutSeconds) * time.Second
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, timeout)
		defer cancel()
		logger.V(4).Info("Applying watch timeout", "seconds", *timeoutSeconds)
	}

	key := s.storageKey(ns, "")
	opts := storage.ListOptions{
		ResourceVersion: reqRV,
		Recursive:       true,
		Predicate:       storage.Everything, // TODO: selection predicate
	}

	w, err := s.storage.Watch(ctx, key, opts)
	if err != nil {
		return errors.NewGRPCError(err, "gpus", "")
	}
	defer w.Stop()

	logger.V(3).Info("Started watch stream", "namespace", ns, "resourceVersion", reqRV)

	for {
		select {
		case <-ctx.Done():
			if ctx.Err() == context.DeadlineExceeded {
				logger.V(3).Info("Watch stream reached requested timeout", "namespace", ns)
				return nil
			}
			logger.V(3).Info("Watch stream closed by client", "namespace", ns)
			return ctx.Err()
		case event, ok := <-w.ResultChan():
			if !ok {
				logger.V(3).Info("Watch stream closed by storage backend", "namespace", ns)
				return nil
			}

			if event.Type == watch.Error {
				if statusObj, ok := event.Object.(*metav1.Status); ok {
					if statusObj.Code == 410 || statusObj.Reason == metav1.StatusReasonExpired {
						logger.V(4).Info("Watch stream expired", "namespace", ns, "resourceVersion", reqRV)
						return status.Errorf(codes.OutOfRange, "required resource version %s is too old: %s", reqRV, statusObj.Message)
					}
					logger.Error(nil, "watch stream storage status error", "status", statusObj.Message)
					return status.Error(codes.Internal, "internal server error")
				}

				if errObj, ok := event.Object.(error); ok && storage.IsInvalidError(errObj) {
					return status.Errorf(codes.OutOfRange, "%v", errObj)
				}
				logger.Error(nil, "unexpected storage error during watch", "object", event.Object)
				return status.Error(codes.Internal, "internal server error")
			}

			obj, ok := event.Object.(*devicev1alpha1.GPU)
			if !ok {
				logger.V(4).Info("Watch received unexpected object type", "type", reflect.TypeOf(event.Object))
				continue
			}

			logger.V(6).Info("Sending watch event",
				"type", event.Type,
				"name", obj.Name,
				"resourceVersion", obj.ResourceVersion,
			)

			resp := &pb.WatchGpusResponse{
				Type:   string(event.Type),
				Object: devicev1alpha1.ToProto(obj),
			}
			if err := stream.Send(resp); err != nil {
				logger.V(3).Info("Watch stream send error (client likely disconnected)", "err", err)
				return err
			}
		}
	}
}

func (s *gpuService) CreateGpu(ctx context.Context, req *pb.CreateGpuRequest) (*pb.Gpu, error) {
	logger := klog.FromContext(ctx)

	if req.GetGpu() == nil {
		return nil, status.Error(codes.InvalidArgument, "resource body is required")
	}
	if req.GetGpu().GetMetadata() == nil || req.GetGpu().GetMetadata().GetName() == "" {
		return nil, status.Error(codes.InvalidArgument, "metadata.name: Required value")
	}

	name := req.GetGpu().GetMetadata().GetName()
	ns := req.GetGpu().GetMetadata().GetNamespace()
	if ns == "" {
		ns = "default"
	}
	key := s.storageKey(ns, name)

	in := devicev1alpha1.FromProto(req.Gpu)
	in.SetNamespace(ns)
	in.SetUID(uuid.NewUUID())

	now := metav1.Now()
	in.SetCreationTimestamp(now)
	in.SetGeneration(1)

	for i := range in.Status.Conditions {
		if in.Status.Conditions[i].LastTransitionTime.IsZero() {
			in.Status.Conditions[i].LastTransitionTime = now
		}
	}

	out := &devicev1alpha1.GPU{}
	if err := s.storage.Create(ctx, key, in, out, 0); err != nil {
		return nil, errors.NewGRPCError(err, "gpus", name)
	}

	logger.V(2).Info("Successfully created GPU", "name", name, "namespace", ns, "uid", out.UID)

	return devicev1alpha1.ToProto(out), nil
}

func (s *gpuService) UpdateGpu(ctx context.Context, req *pb.UpdateGpuRequest) (*pb.Gpu, error) {
	logger := klog.FromContext(ctx)

	if req.GetGpu() == nil {
		return nil, status.Error(codes.InvalidArgument, "resource body is required")
	}
	if req.GetGpu().GetMetadata() == nil || req.GetGpu().GetMetadata().GetName() == "" {
		return nil, status.Error(codes.InvalidArgument, "metadata.name: Required value")
	}

	name := req.GetGpu().GetMetadata().GetName()
	ns := req.GetGpu().GetMetadata().GetNamespace()
	key := s.storageKey(ns, name)

	updated := &devicev1alpha1.GPU{}
	err := s.storage.GuaranteedUpdate(
		ctx,
		key,
		updated,
		false, // ignoreNotFound
		nil,   // TODO: preconditions
		func(input runtime.Object, res storage.ResponseMeta) (runtime.Object, *uint64, error) {
			curr := input.(*devicev1alpha1.GPU)
			incoming := devicev1alpha1.FromProto(req.GetGpu())

			if incoming.ResourceVersion != "" && incoming.ResourceVersion != curr.ResourceVersion {
				return nil, nil, storage.NewResourceVersionConflictsError(key, 0)
			}

			if incoming.UID != "" && incoming.UID != curr.UID {
				return nil, nil, status.Errorf(codes.InvalidArgument,
					"GPU %q is invalid: metadata.uid: field is immutable", name)
			}

			if incoming.Namespace != "" && incoming.Namespace != curr.Namespace {
				return nil, nil, status.Errorf(codes.InvalidArgument,
					"GPU %q is invalid: metadata.namespace: field is immutable", name)
			}

			if reflect.DeepEqual(curr.Spec, incoming.Spec) {
				return curr, nil, nil
			}

			clone := curr.DeepCopy()
			clone.Spec = incoming.Spec
			clone.Generation++

			return clone, nil, nil
		},
		nil, // TODO: cachedExistingObject
	)

	if err != nil {
		return nil, errors.NewGRPCError(err, "gpus", name)
	}

	logger.V(2).Info("Successfully updated GPU",
		"name", name,
		"namespace", ns,
		"resourceVersion", updated.ResourceVersion,
		"generation", updated.Generation,
	)

	return devicev1alpha1.ToProto(updated), nil
}

func (s *gpuService) UpdateGpuStatus(ctx context.Context, req *pb.UpdateGpuStatusRequest) (*pb.Gpu, error) {
	logger := klog.FromContext(ctx)

	if req.GetGpu() == nil {
		return nil, status.Error(codes.InvalidArgument, "resource body is required")
	}
	if req.GetGpu().GetMetadata() == nil || req.GetGpu().GetMetadata().GetName() == "" {
		return nil, status.Error(codes.InvalidArgument, "metadata.name: Required value")
	}

	name := req.GetGpu().GetMetadata().GetName()
	ns := req.GetGpu().GetMetadata().GetNamespace()
	key := s.storageKey(ns, name)

	updated := &devicev1alpha1.GPU{}
	err := s.storage.GuaranteedUpdate(
		ctx,
		key,
		updated,
		false, // ignoreNotFound: Status updates require the object to exist
		nil,   // preconditions
		func(input runtime.Object, res storage.ResponseMeta) (runtime.Object, *uint64, error) {
			curr := input.(*devicev1alpha1.GPU)
			incoming := devicev1alpha1.FromProto(req.GetGpu())

			if incoming.ResourceVersion != "" && incoming.ResourceVersion != curr.ResourceVersion {
				return nil, nil, storage.NewResourceVersionConflictsError(key, 0)
			}

			if incoming.UID != "" && incoming.UID != curr.UID {
				return nil, nil, status.Errorf(codes.InvalidArgument,
					"GPU %q is invalid: metadata.uid: field is immutable", name)
			}

			if incoming.Namespace != "" && incoming.Namespace != curr.Namespace {
				return nil, nil, status.Errorf(codes.InvalidArgument,
					"GPU %q is invalid: metadata.namespace: field is immutable", name)
			}

			if reflect.DeepEqual(curr.Status, incoming.Status) {
				return curr, nil, nil
			}

			clone := curr.DeepCopy()
			clone.Status = incoming.Status

			return clone, nil, nil
		},
		nil,
	)

	if err != nil {
		return nil, errors.NewGRPCError(err, "gpus", name)
	}

	logger.V(2).Info("Successfully updated GPU Status",
		"name", name,
		"namespace", ns,
		"resourceVersion", updated.ResourceVersion,
	)

	return devicev1alpha1.ToProto(updated), nil
}

func (s *gpuService) DeleteGpu(ctx context.Context, req *pb.DeleteGpuRequest) (*emptypb.Empty, error) {
	logger := klog.FromContext(ctx)

	if req.GetName() == "" {
		return nil, status.Error(codes.InvalidArgument, "name is required")
	}

	name := req.GetName()
	ns := req.GetNamespace()
	if ns == "" {
		ns = "default"
	}
	key := s.storageKey(ns, name)

	out := &devicev1alpha1.GPU{}
	if err := s.storage.Delete(
		ctx,
		key,
		out,
		nil, // TODO: preconditions (e.g., rv check)
		storage.ValidateAllObjectFunc,
		nil,                     // TODO: cachedExistingObject
		storage.DeleteOptions{}, // TODO: DeleteOptions
	); err != nil {
		return nil, errors.NewGRPCError(err, "gpus", name)
	}

	logger.V(2).Info("Successfully deleted GPU",
		"name", name,
		"namespace", ns,
		"uid", out.UID,
		"resourceVersion", out.ResourceVersion,
	)

	return &emptypb.Empty{}, nil
}
