//  Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

// Code generated by service-gen. DO NOT EDIT.

package v1alpha1

import (
	devicev1alpha1 "github.com/nvidia/nvsentinel/api/device/v1alpha1"
	pb "github.com/nvidia/nvsentinel/internal/generated/device/v1alpha1"
	"github.com/nvidia/nvsentinel/pkg/controlplane/apiserver/api"
	"github.com/nvidia/nvsentinel/pkg/controlplane/apiserver/registry"
	"github.com/nvidia/nvsentinel/pkg/storage"
	"google.golang.org/grpc"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/runtime/serializer"
)

func init() {
	registry.Register(NewGPUProvider())
}

type gpuServiceProvider struct{}

func NewGPUProvider() api.ServiceProvider {
	return &gpuServiceProvider{}
}

func (p *gpuServiceProvider) GroupName() string {
	return devicev1alpha1.SchemeGroupVersion.Group
}

func (p *gpuServiceProvider) GroupVersion() schema.GroupVersion {
	return devicev1alpha1.SchemeGroupVersion
}

func (p *gpuServiceProvider) BuildGroupInfo() *api.APIGroupInfo {
	return &api.APIGroupInfo{
		GroupName: p.GroupName(),
		VersionedInstallers: map[string]api.RegistrationFunc{
			"v1alpha1": func(f storage.StorageFactory, nodeName string, svr *grpc.Server) error {
				gv := devicev1alpha1.SchemeGroupVersion

				scheme := runtime.NewScheme()
				_ = devicev1alpha1.AddToScheme(scheme)
				codecs := serializer.NewCodecFactory(scheme)
				codec := codecs.LegacyCodec(gv)

				s, err := f.NewStorage("/registry", codec,
					func() runtime.Object { return &devicev1alpha1.GPU{} },
					func() runtime.Object { return &devicev1alpha1.GPUList{} },
				)
				if err != nil {
					return err
				}

				pb.RegisterGpuServiceServer(svr, NewGPUService(s, nodeName))
				return nil
			},
		},
	}
}
